import type { Metadata } from "next";
<<<<<<< HEAD
import "./globals.css";
import React from "react";
import Provider from "@/Provider";

export const metadata: Metadata = {
  title: "Snapkart",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
>>>>>>> bafa9275502d3f80c96e7ae5d5e87887f748a526
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className="w-full min-h-screen bg-gradient-to-b from-green-50 to-white">
       <Provider>
        {children}
        </Provider>

        {/* <div><p>hello</p></div> */}
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> bafa9275502d3f80c96e7ae5d5e87887f748a526
      </body>
    </html>
  );
}
